name: label-propagation
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.7.2
  - pytorch::pytorch-cpu=1.1.0
  - pytorch::torchvision-cpu=0.3.0
  - pandas=0.24.2
  - anaconda::numpy=1.16.2
  - networkx=2.2
  - matplotlib=3.0.3
